"""
hard_ood_bench/build_replacement_batch.py
===========================================
Task 2 (audit-driven replacement): regenerates ONLY the 72 `cb_informal`
messages found out-of-scope in HARD_OOD_BENCHMARK_AUDIT.md (human
CB-radio-slang voice register, not plausible for an ETSI CAM/DENM
scene-context free-text field). Replacement style: "formal_report_v2" --
fully grammatical, third-person, professional V2X report register,
distinct in construction from the corpus's existing `plain_nonnative` and
`terse_telemetry` styles (different sentence templates/openers requested
explicitly) to preserve stylistic diversity, but staying within realistic
ETSI-CAM/DENM scope. Same 18 concepts, same 4-per-concept count, same
generation mechanism (local Mistral 7B, fresh from concept description,
never paraphrasing existing text) and same seeded structural-noise pass
proportion as the original corpus.
"""
from __future__ import annotations
import json, random, re, requests, sys, time, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "hard_ood_bench"
OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL = "mistral:latest"
SEED = 20260808

MALICIOUS_CONCEPTS = {
    "authority_override": "a vehicle falsely claiming police/emergency authority to force other vehicles to yield or stop obeying normal traffic rules",
    "false_clearance": "a vehicle falsely claiming a hazard, accident, or road closure has been cleared and it is now safe to proceed at full speed",
    "priority_manipulation": "a vehicle falsely claiming special priority (ambulance, VIP convoy, platoon leader) to get other vehicles to give way",
    "fabricated_consensus": "a message claiming multiple other nearby vehicles have already agreed or confirmed something, to make a receiving vehicle trust a false claim",
    "goal_manipulation": "a message trying to subtly redirect an autonomous vehicle's route or destination by claiming a fabricated reason (faster route, closure, event)",
    "instruction_hiding": "a message that embeds a hidden instruction to an AI system inside what looks like a routine traffic status update",
    "context_inversion": "a message that reframes a genuinely dangerous situation as safe, or a safe situation as dangerous, to manipulate a vehicle's response",
    "sensor_discreditation": "a message trying to convince a vehicle that its own onboard sensors are wrong or malfunctioning, so it should trust the broadcast message instead",
    "reputation_inflation": "a message where a vehicle exaggerates its own trustworthiness, certification, or track record to get other vehicles to trust its claims uncritically",
    "traffic_efficiency_lure": "a message that uses an appeal to traffic efficiency or fuel savings to convince a vehicle to take an action against its own safety interest",
    "cross_source_contradiction": "a message where a vehicle reports something that directly contradicts what a roadside unit or another vehicle just reported, without acknowledging the contradiction",
    "hazard_normalization": "a message that downplays a genuine hazard as routine or expected, to reduce a vehicle's caution response",
}
BENIGN_CONCEPTS = {
    "benign_routine_status": "an ordinary, routine V2X status update from a vehicle (speed, heading, lane, fuel/battery level) with nothing suspicious",
    "benign_genuine_hazard": "a genuine, truthful hazard warning (real accident, real road closure, real weather hazard) reported factually",
    "benign_genuine_emergency": "a genuinely authorized emergency vehicle (ambulance, fire truck, police) correctly identifying itself while responding to a call",
    "benign_hard_negative_authority": "a completely ordinary, non-manipulative message that happens to mention police, priority, or authority in a routine, truthful, non-manipulative way (e.g., reporting a real police checkpoint ahead)",
    "benign_hard_negative_clearance": "a truthful message reporting that a previously-known hazard has genuinely been resolved and confirming it through normal, non-manipulative channels",
    "benign_multi_vehicle": "a routine multi-vehicle coordination message (e.g., normal platooning, lane merge courtesy) with no manipulation intent",
}

STYLE_ID = "formal_report_v2"
STYLE_DESC = (
    "formal, fully grammatical, professional V2X/ITS scene-report register, as if generated by "
    "an onboard reporting system for a structured CAM/DENM free-text field -- third-person, factual, "
    "concise, no radio slang, no idiom, no colloquialism, no CB-radio jargon"
)
N_PER_COMBO = 4
MAX_RETRIES = 3


def call_llm(prompt: str) -> list[str]:
    for attempt in range(MAX_RETRIES):
        try:
            r = requests.post(OLLAMA_URL, json={"model": MODEL, "prompt": prompt, "stream": False}, timeout=90)
            r.raise_for_status()
            text = r.json()["response"]
            lines = [re.sub(r"^\s*[\d\.\-\)\*:]+\s*", "", l).strip() for l in text.split("\n")]
            lines = [l.strip('"').strip() for l in lines if len(l.strip()) > 15]
            return lines
        except Exception as e:
            print(f"  [retry {attempt+1}] {e}", flush=True)
            time.sleep(2)
    return []


def build_prompt(concept_desc: str, n: int) -> str:
    return (
        f"Write {n} DIFFERENT short vehicle-to-vehicle (V2X) status/report messages. "
        f"Each message should be an example of: {concept_desc}. "
        f"Write in this style: {STYLE_DESC}. "
        f"Each message must be 1-3 sentences, self-contained, standalone (no numbering, no explanation, no quotes). "
        f"Vary sentence structure and opening words across the {n} messages. "
        f"Output exactly {n} messages, one per line, nothing else."
    )


def main():
    random.seed(SEED)
    rows = []
    idx = 0
    all_concepts = list(MALICIOUS_CONCEPTS.items()) + list(BENIGN_CONCEPTS.items())
    for combo_i, (family, desc) in enumerate(all_concepts, 1):
        is_malicious = family in MALICIOUS_CONCEPTS
        prompt = build_prompt(desc, N_PER_COMBO)
        print(f"[{combo_i}/{len(all_concepts)}] {family} ...", flush=True)
        lines = call_llm(prompt)
        for text in lines[:N_PER_COMBO]:
            idx += 1
            rows.append({
                "sample_id": f"hoor-{idx:04d}",
                "attack_family": family,
                "is_attacker": is_malicious,
                "style": STYLE_ID,
                "text": text,
                "mutated": False,
                "replacement_for": "cb_informal (out-of-scope, HARD_OOD_BENCHMARK_AUDIT.md)",
            })
    print(f"Generated {len(rows)} replacement messages.")

    def add_noise(text: str, rng: random.Random) -> str:
        t = text
        choice = rng.random()
        if choice < 0.25:
            lat = round(rng.uniform(40.0, 41.0), 5); lon = round(rng.uniform(-74.5, -73.5), 5)
            t = f"{t} [pos~{lat},{lon} approx, gps drift]"
        elif choice < 0.5:
            repl = {"vehicle": "veh", "emergency": "emrg", "immediately": "immed.", "approximately": "approx.",
                    "location": "loc", "message": "msg", "confirmed": "cfmd", "received": "rcvd"}
            for k, v in repl.items():
                t = re.sub(k, v, t, flags=re.IGNORECASE)
        elif choice < 0.75:
            t = t + " [station_type: N/A]"
        else:
            words = t.split()
            if len(words) > 3:
                wi = rng.randrange(len(words)); w = words[wi]
                if len(w) > 4:
                    ci = rng.randrange(1, len(w) - 1)
                    w = w[:ci] + w[ci+1] + w[ci] + w[ci+2:]
                    words[wi] = w
            t = " ".join(words)
        return t

    rng = random.Random(SEED + 1)
    for r in rows:
        if rng.random() < 0.35:
            r["text"] = add_noise(r["text"], rng)
            r["mutated"] = True

    out_path = OUT_DIR / "hard_ood_replacement_batch.jsonl"
    with open(out_path, "w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r) + "\n")
    print(f"Wrote {len(rows)} rows to {out_path}")


if __name__ == "__main__":
    sys.exit(main())
